services:
  openldap:
    container_name: openldap
    build: ../docker/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANIZATION: "${LDAP_ORGANIZATION}"
      LDAP_DOMAIN: "${LDAP_DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_ADMIN_USERNAME: "${LDAP_ADMIN_USERNAME}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_BIND_USERNAME: "${LDAP_BIND_USERNAME}"
      LDAP_BIND_PASSWORD: "${LDAP_BIND_PASSWORD}"
      LDAP_DEFAULT_USERNAME: "${LDAP_DEFAULT_USERNAME}"
      LDAP_DEFAULT_PASSWORD: "${LDAP_DEFAULT_PASSWORD}"

  lam:
    container_name: lam
    image: ghcr.io/ldapaccountmanager/lam:stable
    depends_on:
      - openldap
    ports:
      - "80:80"
    environment:
      LAM_SKIP_PRECONFIGURE: "false"
      LDAP_DOMAIN: "${LDAP_DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_USERS_DN: "ou=users,${LDAP_BASE_DN}"
      LDAP_GROUPS_DN: "ou=groups,${LDAP_BASE_DN}"
      LDAP_SERVER: "${LDAP_SERVER}"
      LDAP_USER: "cn=admin,${LDAP_BASE_DN}"
      LAM_LANG: "en_US"
      LAM_PASSWORD: "password"